# Requires:
#  - DOCKER_IMAGE_NAME
#  - DOCKER_IMAGE_REGISTRY_USER
#  - DOCKER_IMAGE_NAME_COMMIT_HASH

# Options:
#  - DOCKER_IMAGE_PUSH_DEPS

.PHONY: docker-image-push
docker-image-push: $(DOCKER_IMAGE_PUSH_DEPS)
	docker tag $(DOCKER_IMAGE_NAME) $(DOCKER_IMAGE_REGISTRY_USER)/$(DOCKER_IMAGE_NAME_COMMIT_HASH) && \
	docker push $(DOCKER_IMAGE_REGISTRY_USER)/$(DOCKER_IMAGE_NAME_COMMIT_HASH)
