# Required variables:
# - GOOGLE_CLOUD_PROJECT_LOCAL
#
# Defined variables:
# - APISVR_ENVS_BASE
# - APISVR_ENV_VARS

APISVR_ENVS_BASE=\
	GOOGLE_CLOUD_PROJECT=$(GOOGLE_CLOUD_PROJECT_LOCAL)
APISVR_ENV_VARS=\
	APP_STAGE \
	APP_CORS_ALLOW_ORIGINS \
	APP_FIREBASE_API_KEY \
	FIREBASE_AUTH_EMULATOR_HOST
