# Required variables:
# - APP_PORT_UISVR_dev
# - APP_PORT_UISVR_e2e_test
# - APP_PORT_FIREBASE_AUTH_dev
# - GOOGLE_CLOUD_PROJECT_LOCAL
#
# Defined variables:
# - APP_CORS_ALLOW_ORIGINS
# - FIREBASE_AUTH_EMULATOR_HOST
# - APISVR_ENVS_BASE
# - APISVR_ENV_VARS

APP_CORS_ALLOW_ORIGINS?=http://localhost:$(APP_PORT_UISVR_dev),http://localhost:$(APP_PORT_UISVR_e2e_test)
FIREBASE_AUTH_EMULATOR_HOST?="127.0.0.1:$(APP_PORT_FIREBASE_AUTH_dev)"

APISVR_ENVS_BASE=\
	GOOGLE_CLOUD_PROJECT=$(GOOGLE_CLOUD_PROJECT_LOCAL)
APISVR_ENV_VARS=\
	APP_STAGE \
	APP_CORS_ALLOW_ORIGINS \
	APP_FIREBASE_API_KEY \
	FIREBASE_AUTH_EMULATOR_HOST
