ifeq ($(MYSQL_USER_PASSWORD),)
MYSQL_CLI_AUTH_OPTS?=-u $(MYSQL_USER_NAME)
else
MYSQL_CLI_AUTH_OPTS?=-u $(MYSQL_USER_NAME) --password=$(MYSQL_USER_PASSWORD)
endif
MYSQL_CLI_OPTS=-h $(MYSQL_HOST) -P $(MYSQL_PORT) $(MYSQL_CLI_AUTH_OPTS)
