MYSQL_LOCATION?=Asia%2FTokyo
MYSQL_OPTIONS?=charset=utf8mb4&parseTime=True&loc=$(MYSQL_LOCATION)
MYSQL_DSN?=$(MYSQL_USER_NAME):$(MYSQL_USER_PASSWORD)@tcp($(MYSQL_HOST):$(MYSQL_PORT))/$(MYSQL_DB_NAME)?$(MYSQL_OPTIONS)
