name: CI

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    # if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        go: ["1.21", "1.22", "1.23"]
    name: Test on Go ${{ matrix.go }}
    env:
      SHAPEAPPMK_BRANCH: ${{ github.ref_name }}
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # https://github.com/actions/setup-go
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Check golang version/env
        run: |
          set -x
          go version
          go env

      - name: build
        run: make build
        working-directory: ./tests

      - name: lint
        run: make lint
        working-directory: ./tests

      - name: setup git
        run: |-
          git config --global user.email foo@example.com && \
          git config --global user.name "Foo Bar" && \
          git config --global init.defaultBranch main

      - name: test
        run: make test
        working-directory: ./tests

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test-result
          path: tests/grounds/**/*
